platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'EnglishLearner' do
  # Pods for EnglishLearner
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!


  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'YouTubeSdk', :path => '../node_modules/react-native-youtube-sdk'

  pod 'RNSecureStorage', :path => '../node_modules/react-native-secure-storage'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

end
